**AIM : Implement Linear Regression Algorithm on the given dataset.**

**Exercise 1: Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn.**


In [281]:
import numpy as np
import torch

In [282]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [283]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[-0.0865,  0.0578, -0.3869]], requires_grad=True)

Biases : 
 tensor([-1.4104], requires_grad=True)


In [284]:
#Defining the model
def model(x):
    return  torch.mm(x, w.t(), out=None) + b

In [285]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[-20.4885],
        [-28.9565],
        [-23.6289],
        [-22.0635],
        [-28.9123]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [286]:
#Defining MSE loss function
def MSELoss(P, T): 
  sum = 0
  n = len(T)
  for j in range(0, n):
    sum += (T[j] - P[j]) * (T[j] - P[j])
  return sum / n

loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])    

MSE Loss :  tensor(11525.2783, grad_fn=<SelectBackward0>)


In [287]:
#Computing Gradient
loss.backward()
print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)


Gradients for weights : 
 tensor([[-16637.9375, -19388.5977, -11785.1650]])

Gradient for biases: 
 tensor([-202.0199])


In [288]:
#Adjusting weights and biases using Gradient Descent
#Reseting gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)

print("\nNew Weights : \n", w)
print("\nNew Biases : \n", b)

Gradients for weights : 
 tensor([[0., 0., 0.]])

Gradient for biases: 
 tensor([0.])

New Weights : 
 tensor([[ 0.0799,  0.2517, -0.2691]], requires_grad=True)

New Biases : 
 tensor([-1.4084], requires_grad=True)


In [289]:
#Calculating  new loss
preds = model(inputs)

loss = MSELoss(preds, targets)
print("New MSE Loss : ", loss[0])  

New MSE Loss :  tensor(5024.4834, grad_fn=<SelectBackward0>)


In [290]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])  

MSE Loss :  tensor(71.6723, grad_fn=<SelectBackward0>)


**Exercise 2: Try Linear regression on same prediction data using Tensorflow**

In [291]:
import torch.nn as nn

In [292]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [293]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[ 0.5873, -0.3283,  0.8151]], requires_grad=True)

Biases : 
 tensor([1.2333], requires_grad=True)


In [294]:
#Defining the model
def model(x):
    return  x @ w.t() + b

In [295]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[57.1585],
        [77.9523],
        [55.6091],
        [77.1801],
        [67.2953]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [296]:
MSELoss = nn.MSELoss()
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss) 

MSE Loss :  tensor(1669.7399, grad_fn=<MseLossBackward0>)


In [297]:
#Computing Gradient
loss.backward()
print("\nGradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)


Gradients for weights : 
 tensor([[-1017.2111, -3895.9434, -1711.8280]])

Gradient for biases: 
 tensor([-18.3219])


In [298]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss)

MSE Loss :  tensor(117.6809, grad_fn=<MseLossBackward0>)
