In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

In [65]:
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [67]:
le = LabelEncoder()

weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
class_label = le.fit_transform(play)

print("Weather :\n", weather_encoded)
print("\nTemperature :\n", temp_encoded)
print("\nPlay :\n", class_label)

Weather :
 [2 2 0 1 1 1 0 2 2 1 2 0 0 1]

Temperature :
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]

Play :
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [68]:
features = tuple(zip(weather_encoded, temp_encoded))

print("Features :\n", features)

Features :
 ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [69]:
model = MultinomialNB()
model.fit(features, class_label)

MultinomialNB()

In [70]:
predicted = model.predict_proba([[2,2]])
print("Weather is Sunny, Temp is Mild =", predicted)

Weather is Sunny, Temp is Mild = [[0.36151612 0.63848388]]


In [71]:
iris=datasets.load_iris()

print("Features :\n", iris.feature_names)
print("\nLabels :\n", iris.target_names)

print("\nData shape : ", iris.data.shape)
print("\nTraget shape : ", iris.target.shape)

# print("\nData :\n", iris.data)
# print("\nTarget :\n", iris.target)

print("\nData type : ", type(iris.data))

newdata = iris.data[50: , :]
newtarget = iris.target[50:]

print("\nNew Data shape : ", newdata.shape)
print("\nNew Traget shape : ", newtarget.shape)

Features :
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels :
 ['setosa' 'versicolor' 'virginica']

Data shape :  (150, 4)

Traget shape :  (150,)

Data type :  <class 'numpy.ndarray'>

New Data shape :  (100, 4)

New Traget shape :  (100,)


In [72]:
data_train, data_test, target_train, target_test = train_test_split(newdata, newtarget, test_size = 0.30, random_state = 9)

gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

print("Accuracy :", metrics.accuracy_score(target_test, target_pred))
print("\nConfusion Matrix :\n", confusion_matrix(target_test, target_pred))

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('\nprecision :', precision)
print('\nrecall :', recall)

Accuracy : 0.9333333333333333

Confusion Matrix :
 [[17  1]
 [ 1 11]]

precision : 0.9444444444444444

recall : 0.9444444444444444


# TASK 1
Try the algo on Dataset2 - LabelEncoding of features:
and Train test Division 90%-10%

In [2]:
data=pd.read_csv('Dataset2.csv')
print(data)

   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [3]:
le=LabelEncoder()
outlook=le.fit_transform(data.Outlook)
print("\noutlook :",data.Outlook)
print("\nEncoded outlook :",outlook)


outlook : 0     R
1     R
2     O
3     S
4     S
5     S
6     O
7     R
8     R
9     S
10    R
11    O
12    O
13    S
Name: Outlook, dtype: object

Encoded outlook : [1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [4]:
temp=le.fit_transform(data.Temp)
print("\n temp :",data.Temp)
print("\nEncoded temp :",temp)
wind=le.fit_transform(data.Wind)
print("\n wind :",data.Wind)
print("\nEncoded wind :",wind)
hum=le.fit_transform(data.Humidity)
print("\nHumdity :",data.Humidity)
print("\nEncoded Humdity :",hum)
res=le.fit_transform(data.Class)
print("\n class :",data.Class)
print("\nEncoded class :",res)


 temp : 0     H
1     H
2     H
3     M
4     M
5     M
6     C
7     C
8     C
9     M
10    M
11    M
12    H
13    M
Name: Temp, dtype: object

Encoded temp : [1 1 1 2 2 2 0 0 0 2 2 2 1 2]

 wind : 0     F
1     T
2     F
3     F
4     F
5     T
6     T
7     F
8     F
9     F
10    T
11    T
12    F
13    T
Name: Wind, dtype: object

Encoded wind : [0 1 0 0 0 1 1 0 0 0 1 1 0 1]

Humdity : 0     Normal
1       High
2     Normal
3     Normal
4     Normal
5        Low
6     Normal
7     Normal
8        Low
9       High
10      High
11       Low
12    Normal
13    Normal
Name: Humidity, dtype: object

Encoded Humdity : [2 0 2 2 2 1 2 2 1 0 0 1 2 2]

 class : 0     N
1     N
2     Y
3     N
4     Y
5     Y
6     Y
7     Y
8     Y
9     Y
10    Y
11    Y
12    Y
13    N
Name: Class, dtype: object

Encoded class : [0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [5]:
features=(tuple)(zip(outlook,temp,wind,hum))
print("Features : ",features)

Features :  ((1, 1, 0, 2), (1, 1, 1, 0), (0, 1, 0, 2), (2, 2, 0, 2), (2, 2, 0, 2), (2, 2, 1, 1), (0, 0, 1, 2), (1, 0, 0, 2), (1, 0, 0, 1), (2, 2, 0, 0), (1, 2, 1, 0), (0, 2, 1, 1), (0, 1, 0, 2), (2, 2, 1, 2))


In [6]:
model=GaussianNB()
model.fit(features,res);

predict=model.predict([[1,2,0,2],[2,0,0,1]])
print("Predicted :  ",predict)

Predicted :   [1 1]


ACCURACY

In [7]:
#testdata=np.array([data.Outlook,data.Temp,data.Wind,data.Humidity])
#tardata=np.array([data.Class])

data_train,data_test,tar_train,tar_test=train_test_split(features,res,test_size=0.1,random_state=61)

In [8]:
gnd=GaussianNB()
gnd.fit(data_train,tar_train)
tar_pred=gnd.predict(data_test)
print("Accuracy :",metrics.accuracy_score(tar_test,tar_pred))

Accuracy : 0.5


In [9]:
print("Confusion Metrix: ",confusion_matrix(tar_test, tar_pred))

Confusion Metrix:  [[0 0]
 [1 1]]


In [10]:
pricision=precision_score(tar_test, tar_pred,average=None)
recall=recall_score(tar_test, tar_pred,average=None)
print("Pricision : {}".format(pricision))
print("Recall : {}".format(recall))

Pricision : [0. 1.]
Recall : [0.  0.5]


C:\Users\nirav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# TASK 2 
Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division
65%-35%

In [59]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("abalone_train.csv",names=["Length", "Diameter", "Height", "Whole weight", "Age"])
data

Length  Diameter  Height  Whole weight  Age
0       5         4       4             2   18
1       6         5       3             3   10
2       4         6       2             5   10
3       3         2       1             6   18
4       4         4       2             6   10
5       5         2       3             5   18
6       6         6       1             3   18
7       4         5       4             2   18
8       3         2       2             2   10

In [60]:
len=data['Length']
length=pd.get_dummies(len)
di=data['Diameter']
dia=pd.get_dummies(di)
he=data['Height']
het=pd.get_dummies(he)
w=data['Whole weight']
wt=pd.get_dummies(w)
le=LabelEncoder()
data.iloc[:,-1]=le.fit_transform(data['Age'])

data = data.drop(['Length', 'Diameter', 'Height', 'Whole weight'], axis = 1)
data = pd.concat([length, dia, het, wt,data], axis = 1)


print("encoded data: ",data)

encoded data:     3  4  5  6  2  4  5  6  1  2  3  4  2  3  5  6  Age
0  0  0  1  0  0  1  0  0  0  0  0  1  1  0  0  0    1
1  0  0  0  1  0  0  1  0  0  0  1  0  0  1  0  0    0
2  0  1  0  0  0  0  0  1  0  1  0  0  0  0  1  0    0
3  1  0  0  0  1  0  0  0  1  0  0  0  0  0  0  1    1
4  0  1  0  0  0  1  0  0  0  1  0  0  0  0  0  1    0
5  0  0  1  0  1  0  0  0  0  0  1  0  0  0  1  0    1
6  0  0  0  1  0  0  0  1  1  0  0  0  0  1  0  0    1
7  0  1  0  0  0  0  1  0  0  0  0  1  1  0  0  0    1
8  1  0  0  0  1  0  0  0  0  1  0  0  1  0  0  0    0


In [61]:
features=data.iloc[:,:-1]
labels=data.iloc[:,-1]
print("Features : ",features)

Features :     3  4  5  6  2  4  5  6  1  2  3  4  2  3  5  6
0  0  0  1  0  0  1  0  0  0  0  0  1  1  0  0  0
1  0  0  0  1  0  0  1  0  0  0  1  0  0  1  0  0
2  0  1  0  0  0  0  0  1  0  1  0  0  0  0  1  0
3  1  0  0  0  1  0  0  0  1  0  0  0  0  0  0  1
4  0  1  0  0  0  1  0  0  0  1  0  0  0  0  0  1
5  0  0  1  0  1  0  0  0  0  0  1  0  0  0  1  0
6  0  0  0  1  0  0  0  1  1  0  0  0  0  1  0  0
7  0  1  0  0  0  0  1  0  0  0  0  1  1  0  0  0
8  1  0  0  0  1  0  0  0  0  1  0  0  1  0  0  0


In [64]:
data_train,data_test,tar_train,tar_test=train_test_split(features,labels,test_size=0.35,random_state=61)

gnd=GaussianNB()

gnd.fit(data_train,tar_train)
tar_pred=gnd.predict(data_test)
print("Accuracy :",metrics.accuracy_score(tar_test,tar_pred))

print("\nConfusion Matrix :\n", confusion_matrix(tar_test, tar_pred))

precision = precision_score(tar_test, tar_pred)
recall = recall_score(tar_test, tar_pred)

print('\nprecision :', precision)
print('\nrecall :', recall)

Accuracy : 0.25

Confusion Matrix :
 [[0 3]
 [0 1]]

precision : 0.25

recall : 1.0
